mdapioutput2/objects/Candidate__c.object
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Average_Score__c</fullName>
        <formula>IF(Number_of_Interviews__c  > 0, Sum_Average_Scores__c  /  Number_of_Interviews__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Average Score on All Interviews</inlineHelpText>
        <label>Average Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Interviews__c</fullName>
        <label>Number of Interviews</label>
        <summaryForeignKey>Interview__c.Candidate__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Candidates</relationshipLabel>
        <relationshipName>Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapioutput2/objects/Interview__c.object
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Interview Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Average_Score__c</fullName>
        <formula>IF(Number_of_Interviewers__c  > 0, Score_Total__c  /  Number_of_Interviewers__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Average Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Interview_Type__c</fullName>
        <inlineHelpText>Enter the Type of Interview</inlineHelpText>
        <label>Interview Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Recruiter Interview</fullName>
                    <default>true</default>
                    <label>Recruiter Interview</label>
                </value>
                <value>
                    <fullName>Technical Interview</fullName>
                </value>
                <value>
                    <fullName>Management Interview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapioutput2/objects/Position__c.object
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Fullfilment_Date_Limit__c</fullName>
        <label>Fulfillment Date Limit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the Position</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed - Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Closed - Not Fulfilled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/MyCustomController.cls
/*
* Copyright (c) 2018, salesforce.com, inc.
* All rights reserved.
* SPDX-License-Identifier: BSD-3-Clause
* For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
*/

public with sharing class MyCustomController {

    private final Account account;

    public MyCustomController() {
        account = new Account();
    }

    public List<Candidate__c> getTopCandidates() {


        Boolean userHasAccesstoField1 = Schema.sObjectType.Candidate__c.fields.id.isAccessible() ;
        Boolean userHasAccesstoField2 = Schema.sObjectType.Candidate__c.fields.Average_Score__c.isAccessible() ;
        Boolean userHasAccesstoField3 = Schema.sObjectType.Candidate__c.fields.Number_of_Interviews__c.isAccessible() ;
        Boolean userHasAccesstoField4 = Schema.sObjectType.Candidate__c.fields.Name.isAccessible() ;
        List<Candidate__c> candidates = null;

        if (userHasAccesstoField1 && userHasAccesstoField2 && userHasAccesstoField3 && userHasAccesstoField4){
        candidates = [SELECT id, Name,Average_Score__c,
                                                          Number_of_Interviews__c FROM Candidate__c 
                                                          order by Number_of_Interviews__c desc, Average_Score__c desc limit 3]; 
                           }
        return candidates; 
    }
    
    
    public List<Position__c> getUpcomingPositions() {

        
        Boolean userHasAccesstoField1 = Schema.sObjectType.Position__c.fields.id.isAccessible() ;
        Boolean userHasAccesstoField2 = Schema.sObjectType.User.fields.name.isAccessible() ;
        Boolean userHasAccesstoField3 = Schema.sObjectType.Position__c.fields.ownerid.isAccessible() ;
        Boolean userHasAccesstoField4 = Schema.sObjectType.Position__c.fields.Name.isAccessible() ;
        Boolean userHasAccesstoField5 = Schema.sObjectType.Position__c.fields.Fullfilment_Date_Limit__c.isAccessible() ;
        Boolean userHasAccesstoField6 = Schema.sObjectType.Position__c.fields.Hiring_Manager__c.isAccessible() ;

        List<Position__c> positions = null;
        
        if (userHasAccesstoField1 && userHasAccesstoField2 && userHasAccesstoField3 && userHasAccesstoField4 && userHasAccesstoField5 && userHasAccesstoField6){
        positions = [SELECT Id,Name,owner.name, ownerid, Fullfilment_Date_Limit__c,Hiring_Manager__c, Hiring_Manager__r.Name,Status__c 
                                                        FROM Position__c 
                                                        where Fullfilment_Date_Limit__c > TODAY 
                                                        order by Fullfilment_Date_Limit__c desc limit 3]; 
                                                    }
        return positions; 
    }
    
    
    public List<Interview__c> getTodaysInterviews() {

        Boolean userHasAccesstoField1 = Schema.sObjectType.Interview__c.fields.id.isAccessible() ;
        Boolean userHasAccesstoField2 = Schema.sObjectType.Candidate__c.fields.name.isAccessible() ;
        Boolean userHasAccesstoField3 = Schema.sObjectType.Interview__c.fields.Candidate__c.isAccessible() ;
        Boolean userHasAccesstoField4 = Schema.sObjectType.Interview__c.fields.Name.isAccessible() ;
        Boolean userHasAccesstoField5 = Schema.sObjectType.Interview__c.fields.Interview_Type__c.isAccessible() ;

        List<Interview__c> interviews = null;
        if (userHasAccesstoField1 && userHasAccesstoField2 && userHasAccesstoField3 && userHasAccesstoField4 && userHasAccesstoField5){
        interviews = [SELECT Id,name,Candidate__c,Candidate__r.Name, Interview_Type__c 
                                                          FROM Interview__c limit 3]; 
                                                      }
        return interviews; 
    }

    public PageReference save() {
        Schema.DescribeSObjectResult drSObj = Schema.sObjectType.Account;
        if (drSObj.isUpdateable()){
            update account;
        }
        return null;
    }
}