mdapioutput2/objects/Candidate__c.object
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>E_mail__c</fullName>
        <label>E-mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>First_Name__c + " " +   Last_Name__c</formula>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Candidates</relationshipLabel>
        <relationshipName>Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Twitter_ID__c</fullName>
        <inlineHelpText>Example @username</inlineHelpText>
        <label>Twitter ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapioutput2/objects/Interview__c.object
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Interview Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <recordTypes>
        <fullName>Technical</fullName>
        <active>true</active>
        <label>Technical</label>
    </recordTypes>
</CustomObject>

mdapioutput/objects/Interviewer__c.object
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <displayFormat>INTW-{0000}</displayFormat>
        <label>Interviewer Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Candidate__c</fullName>
        <formula>Interview__r.Candidate__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Candidate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interview__c</fullName>
        <label>Interview</label>
        <referenceTo>Interview__c</referenceTo>
        <relationshipLabel>Interviewers</relationshipLabel>
        <relationshipName>Interviewers1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Interviewers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <formula>Interview__r.Candidate__r.Position__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position</label>
        <type>Text</type>
    </fields>
</CustomObject>

mdapioutput2/objects/Offer__c.object
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapioutput2/objects/Position__c.object
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapioutput/objects/Twitter_User__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Twitter Users</label>
    <fields>
        <fullName>Token_Secret__c</fullName>
        <label>Token Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapioutput2/classes/Test_Lightning_Apex_Controllers.cls
@isTest
private class Test_Lightning_Apex_Controllers {
	
	@isTest static void test_CandidateGeneralController() {
		// Implement test code
		CandidateGeneralController instance = new CandidateGeneralController();
		List<Candidate__c> lstRecs = instance.getTopCandidates();

	}
	
	@isTest static void test_FilesViewerServerController() {
		// Implement test code
		Test.startTest();

        Account a = TestFactory.insertAccount();

		List<FilesViewerServerController> lstRecs = FilesViewerServerController.getListRecords(a.id, '1');

		Test.stopTest();

	}

	@isTest static void test_GenericListMap_ServerController() {
		// Implement test code
		Test.startTest();

        // insert candidate records with lat long and twitter info

        // recordIds example: 'a0MB0000000cQYIMA2','a0MB0000000cuyfMAA','a0MB0000000drbGMAQ','a0MB0000000cQX5MAM','a0MB0000000cQdNMAU','a0MB0000000cQXKMA2','a0MB0000000cQdIMAU','a0MB0000000cQXoMAM'

        Candidate__c candidateA = TestFactory.insertCandidate('Candidate A', 'Candidate', 'San Francisco', 'r@r.com', 'A', 'CA', '@roreb');
        Candidate__c candidateB = TestFactory.insertCandidate('Candidate B', 'Candidate', 'San Francisco', 'r@r.com', 'B', 'CA', '@roreb');

        String recordIds = '\'' + candidateA.id + '\'' + ',' + '\'' + candidateB.id + '\'';

		List<GenericListMap_ServerController> lstRecs = GenericListMap_ServerController.getListRecords(recordIds, 'Candidate__c', 'Full_Name__c', 'Geolocation__Latitude__s', 'Geolocation__Longitude__s', 'City__c', 'State__c');

		Test.stopTest();

	}

	@isTest static void test_ListServerController() {
		// Implement test code
		Test.startTest();

        Account a = TestFactory.insertAccount();

		List<ListServerController> lstRecs = ListServerController.getListRecords('1', 'Account', 'Name', 'ACME Inc.' , 'Id', 'AccountNumber', 'Site', 'AccountSource', 'Phone', 'Name', 'asc');

		Test.stopTest();

	}

	@isTest static void test_Modal_Record_Detail_Controller() {
		// Implement test code
		Test.startTest();

        Account a = TestFactory.insertAccount();

		List<Modal_Record_Detail_Controller> lstRecs = Modal_Record_Detail_Controller.getListRecords(a.id, 'Account', 'Name', 'AccountSource', 'AccountNumber', 'Site');

		Test.stopTest();

	}
	
	@isTest static void test_RecordTimelineServerController() {
		// Implement test code
		Test.startTest();

        Account a = TestFactory.insertAccount();
        Contact c = TestFactory.insertContact('FirstName', 'LastName', a.id);

		List<RecordTimelineServerController> lstRecs = RecordTimelineServerController.getListRecords(a.id, '1', 'Contact', 'FirstName', 'FirstName', 'CreatedDate', 'CreatedDate', 'AccountId', 'Description', 'Department', 'Title', 'Phone');

		Test.stopTest();

	}

	@IsTest(SeeAllData=true) static void test_ReferralsServerController() {
		// Implement test code
		Test.startTest();

        Account a = TestFactory.insertAccount();
        Contact c = TestFactory.insertContact('FirstName', 'LastName', a.id);

		List<ReferralsServerController> lstRecs = ReferralsServerController.getListRecords('1', a.id, 'Contact', 'AccountId', 'FirstName', 'FirstName', 'OwnerId', 'Owner', 'LastName');

		Test.stopTest();

	}

	@IsTest(SeeAllData=true) static void test_RelatedListServerController() {
		// Implement test code
		Test.startTest();

        Account a = TestFactory.insertAccount();
        Contact c = TestFactory.insertContact('FirstName', 'LastName', a.id);

		List<RelatedListServerController> lstRecs = RelatedListServerController.getListRecords('1', a.id, 'Contact', 'AccountId', 'FirstName', 'FirstName', 'OwnerId', 'Owner', 'LastName');

		Test.stopTest();

	}

	@isTest static void test_Twitter_Lightning_Controller() {
		// Implement test code
		

        // insert candidate records with lat long and twitter info

        Candidate__c candidateA = TestFactory.insertCandidate('Candidate A', 'Candidate', 'San Francisco', 'r@r.com', 'A', 'CA', '@roreb');

		// Create Custom Settings for test:

        Twitter_User__c cstRecord = new Twitter_User__c(Name = 'TwitterApp',
    	Token_Secret__c  = 'LETjbmGTLmKF9tBldLY8gbNH3pwCgbg7o6ocSixKrkbdRbeJDx',
    	Token__c  = 'crTSqn98nBWCC8lbj0IauMv06');
        Database.UpsertResult urList = Database.upsert(cstRecord, true);

        Test.startTest();
        Boolean hasTwitId = Twitter_Lightning_Controller.hasTwitterID(candidateA.id, 'Candidate__c', 'Twitter_ID__c');

        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new WebServiceMockImpl());

        Twitter_Lightning_Controller rec = Twitter_Lightning_Controller.getRecordDetails(candidateA.id, 'Candidate__c', 'Twitter_ID__c', 'First_Name__c', 'Last_Name__c', 'Company__c', 'E_mail__c');

        

		Twitter_Lightning_Controller recPicture = Twitter_Lightning_Controller.getTwitterPicture(candidateA.id, 'Candidate__c', 'Twitter_ID__c');

		Twitter_Lightning_Controller rec2 = Twitter_Lightning_Controller.getTwitterUser('@roreb', 'Candidate', 'A', '', 'r@r.com');

		Test.stopTest();

	}

	@isTest static void test_MyCustomController() {
		// Implement test code
		Test.startTest();

        MyCustomController ref = new MyCustomController();
        
        Candidate__c candidateA = TestFactory.insertCandidate('Candidate A', 'Candidate', 'San Francisco', 'r@r.com', 'A', 'CA', '@roreb');
        List<Candidate__c> lstCands = ref.getTopCandidates();

        Position__c positionA = TestFactory.insertPosition('Position1', 'Open');
        List<Position__c> lstPositions = ref.getUpcomingPositions();

        Interview__c interviewA = TestFactory.insertInterview(candidateA.id, 'Technical Interview', 'Pending');
        List<Interview__c> lstInterviews = ref.getTodaysInterviews();

		Test.stopTest();

	}

	@isTest static void test_myControllerExtension() {
		// Implement test code
		Test.startTest();

        Candidate__c candidateA = TestFactory.insertCandidate('Candidate A', 'Candidate', 'San Francisco', 'r@r.com', 'A', 'CA', '@roreb');

        Interview__c interviewA = TestFactory.insertInterview(candidateA.id, 'Technical Interview', 'Pending');

        Interviewer__c interviewerA = TestFactory.insertInterviewer(interviewA.id);


        ApexPages.currentPage().getParameters().put('id',interviewerA.id);
		ApexPages.StandardController stdInterviewer = new ApexPages.StandardController(interviewerA);
	    myControllerExtension objMyControllerExtension  = new myControllerExtension(stdInterviewer);
		
		objMyControllerExtension.getGreeting();
		objMyControllerExtension.getItems();
        
        
		Test.stopTest();

	}

	@isTest static void testInstallScript() {
	  	Sparkle_After_Install postinstall = new Sparkle_After_Install();
	    Test.testInstall(postinstall, null);
	    
  }

  @isTest static void test_Sparkle_Helper() {
	  	
  		/*Test.startTest();

        Candidate__c candidateA = TestFactory.insertCandidate('Candidate A', 'Candidate', 'San Francisco', 'r@r.com', 'A', 'CA', '@roreb');

        Interview__c interviewA = TestFactory.insertInterview(candidateA.id, 'Technical Interview', 'Pending');

        Interviewer__c interviewerA = TestFactory.insertInterviewer(interviewA.id);

	  	String returnValue = Sparkle_Helper.GetSobjectField(interviewerA, 'Id');
	  	//String returnValue2 = Sparkle_Helper.GetSobjectField(interviewerA, 'CreatedBy.Id');
	  	String returnValue3 = Sparkle_Helper.GetSobjectField(interviewerA, 'Interview__r.Name');
	  	String returnValue4 = Sparkle_Helper.GetSobjectField(interviewerA, 'Interview__r.Candidate__r.Name');

	  	Test.stopTest(); */
	    
  }
    
   @isTest static void test_OfferLetterCompController() {
		// Implement test code
		Test.startTest();
		Position__c positionA = TestFactory.insertPosition('Position1', 'Open');
        Candidate__c candidateA = TestFactory.insertCandidateWithPosition('Candidate A', 'Candidate', 'San Francisco', 'r@r.com', 'A', 'CA', '@roreb', positionA.id);
		
        // Test getEmailTemplatesNames method:
		List<OfferLetterCompController> lstRecs = OfferLetterCompController.getEmailTemplatesNames(candidateA.id);
      	
        Double salary = 10000;
        Double bonus = 5000;
        
      	Offer__c offerA = TestFactory.insertOffer(candidateA.id, salary, bonus);
      	EmailTemplate templateA = [SELECT Id FROM EmailTemplate where Folder.Name = 'Recruitment Templates' LIMIT 1];
        System.debug('templateA: ' + templateA);
        
        // Test getEmailTemplatebyId method:
      	List<OfferLetterCompController> lstRecs2 = OfferLetterCompController.getEmailTemplatebyId(templateA.id, candidateA.id, offerA.id);

        
        // Test upsertOfferRecord method:
        String lstRecs3 =  OfferLetterCompController.upsertOfferRecord(offerA.id, candidateA.id, salary, bonus);
        String lstRecs4 =  OfferLetterCompController.upsertOfferRecord(null, candidateA.id, salary, bonus);
        
        // Test sendEmail method:
        
        OfferLetterCompController.sendEmail('test body', 'test subject', 'r@r.com', offerA.id);
        
      	Test.stopTest();
	}

}