mdapioutput2/objects/Candidate__c.object
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Average_Score__c</fullName>
        <formula>IF(Number_of_Interviews__c  > 0, Sum_Average_Scores__c  /  Number_of_Interviews__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Average Score on All Interviews</inlineHelpText>
        <label>Average Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Interviews__c</fullName>
        <label>Number of Interviews</label>
        <summaryForeignKey>Interview__c.Candidate__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

force-app/main/default/classes/CandidateGeneralController.cls
/*
* Copyright (c) 2018, salesforce.com, inc.
* All rights reserved.
* SPDX-License-Identifier: BSD-3-Clause
* For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
*/
public with sharing class CandidateGeneralController {
    
    
    
    public List<Candidate__c> getTopCandidates() {

    	Boolean userHasAccesstoField1 = Schema.sObjectType.Candidate__c.fields.id.isAccessible() ;
        Boolean userHasAccesstoField2 = Schema.sObjectType.Candidate__c.fields.Average_Score__c.isAccessible() ;
        Boolean userHasAccesstoField3 = Schema.sObjectType.Candidate__c.fields.Number_of_Interviews__c.isAccessible() ;
        Boolean userHasAccesstoField4 = Schema.sObjectType.Candidate__c.fields.Name.isAccessible() ;

        List<Candidate__c> candidates = null;
        
        if (userHasAccesstoField1 && userHasAccesstoField2 && userHasAccesstoField3 && userHasAccesstoField4){
        candidates = [SELECT id, Name,Average_Score__c, Number_of_Interviews__c FROM Candidate__c order by Number_of_Interviews__c desc, Average_Score__c desc limit 5]; 
                                                      }
        return candidates; 
    }
    

}