mdapioutput2/objects/Candidate__c.object
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>E_mail__c</fullName>
        <label>E-mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Candidates</relationshipLabel>
        <relationshipName>Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Twitter_ID__c</fullName>
        <inlineHelpText>Example @username</inlineHelpText>
        <label>Twitter ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapioutput2/objects/Interview__c.object
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Interview Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Interview_Date__c</fullName>
        <label>Interview Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interview_Type__c</fullName>
        <inlineHelpText>Enter the Type of Interview</inlineHelpText>
        <label>Interview Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Recruiter Interview</fullName>
                    <default>true</default>
                    <label>Recruiter Interview</label>
                </value>
                <value>
                    <fullName>Technical Interview</fullName>
                </value>
                <value>
                    <fullName>Management Interview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapioutput/objects/Interviewer__c.object
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <displayFormat>INTW-{0000}</displayFormat>
        <label>Interviewer Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Candidate__c</fullName>
        <formula>Interview__r.Candidate__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Candidate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interview_Type__c</fullName>
        <formula>TEXT(Interview__r.Interview_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Interview Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interview__c</fullName>
        <label>Interview</label>
        <referenceTo>Interview__c</referenceTo>
        <relationshipLabel>Interviewers</relationshipLabel>
        <relationshipName>Interviewers1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Interviewers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <formula>Interview__r.Candidate__r.Position__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position</label>
        <type>Text</type>
    </fields>
</CustomObject>

mdapioutput2/objects/Offer__c.object
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Annual_Bonus_Amount__c</fullName>
        <label>Annual Bonus Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Annual_Salary_Offered_Amount__c</fullName>
        <label>Annual Salary Offered Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

mdapioutput2/objects/Position__c.object
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Fullfilment_Date_Limit__c</fullName>
        <label>Fulfillment Date Limit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the Position</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed - Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Closed - Not Fulfilled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/TestFactory.cls
@isTest
public class TestFactory {
    // define default constants that can be accessible to assert against.

    public static final String DEFAULT_ACCOUNT_NAME = 'ACME Inc.';


    /* The “create” methods are used to instantiate the sobjects without inserting them. 
       This is tremendously helpful when you need to create a particular record and then tweak it before 
       it’s inserted from the calling code. */  

    
    public static Account createAccount(){

          return createAccount(DEFAULT_ACCOUNT_NAME);

    }

 

    /* The create methods are commonly overloaded to allow different properties to be set. */

    public static Account createAccount(String name){

           return new Account(

               Name = name

           );

    }
    

    public static Contact createContact(String fname, String lname,  String accountID){

           return new Contact(

               FirstName = fname,
               LastName = lname,
               Accountid = accountID

           );

    }

    public static EntitySubscription createEntitySubs(id prentID, id subscrID){

           return new EntitySubscription(

               ParentId = prentID,
               SubscriberId = subscrID

           );

    }

    public static Candidate__c createCandidate(String name, String fname, String city, String email, String lname, String state, String twitterid){

           return new Candidate__c(
           	   Name = name,
               First_Name__c = fname,
               City__c = city,
               E_mail__c = email,
               Last_Name__c = lname,
               State__c = state,
               Twitter_ID__c = twitterid

           );

    }
    
    public static Candidate__c createCandidateWithPosition(String name, String fname, String city, String email, String lname, String state, String twitterid, String positionId){

           return new Candidate__c(
           	   Name = name,
               First_Name__c = fname,
               City__c = city,
               E_mail__c = email,
               Last_Name__c = lname,
               State__c = state,
               Twitter_ID__c = twitterid,
               Position__c = positionId

           );

    }

    public static Position__c createPosition(String name, String recStatus){

    	Date todaysDt = Date.today();
    	Date fDate = todaysDt.addMonths(6);

           return new Position__c(
           	   Name = name,
               Status__c = recStatus,
               Fullfilment_Date_Limit__c = fDate

           );

    }

    public static Interview__c createInterview(String candidateId, String recType, String recStatus){

    	DateTime myDateTime = datetime.now();
    	DateTime fDate = myDateTime.addMonths(1);

           return new Interview__c(
           	   Candidate__c = candidateId,
               Status__c = recStatus,
               Interview_Date__c = fDate,
               Interview_Type__c = recType

           );

    }

	public static Interviewer__c createInterviewer(String interviewId){

           return new Interviewer__c(
           	   Interview__c = interviewId

           );

    } 
    
    
    public static Offer__c createOffer(String candidateId, Double salary, Double bonus){

           return new Offer__c(
           	   Candidate__c = candidateId, 
               Annual_Salary_Offered_Amount__c = salary, 
               Annual_Bonus_Amount__c  = bonus

           );

    }
    
    /*
    public static EmailTemplate createEmailTemplate(String Body,FolderId,HtmlValue,Id,IsActive,Name,NamespacePrefix,OwnerId,Subject){

           return new Offer__c(
           	   Candidate__c = candidateId, 
               Annual_Salary_Offered_Amount__c = salary, 
               Annual_Bonus_Amount__c  = bonus

           );

    }
*/

    /* The “Insert” methods are used to create the sobjects and then insert them. They delegate 
       the creation to the create methods and then insert the records. Like the create methods,
       the insert methods are overloaded to allow different properties to be set as necessary.
       Another best practice is to bulk insert or bulk create data, but to keep the sample short, that’s omitted. */

    public static Account insertAccount(){

          Account accountToInsert = createAccount();
          insert accountToInsert;
          return accountToInsert;

    }

    public static Contact insertContact(String fname, String lname,  String accountID){

          Contact contactToInsert = createContact(fname, lname, accountID);
          insert contactToInsert;
          return contactToInsert;

    }
    
    public static EntitySubscription insertEntitySubscription(id parentID, id subscriberID){

          EntitySubscription entToInsert = createEntitySubs(parentID, subscriberID);
          insert entToInsert;
          return entToInsert;

    }

    public static Candidate__c insertCandidate(String name, String fname, String city, String email, String lname, String state, String twitterid){

          Candidate__c entToInsert = createCandidate(name, fname, city, email, lname, state, twitterid);
          insert entToInsert;
          return entToInsert;

    }
    
    public static Candidate__c insertCandidatewithPosition(String name, String fname, String city, String email, String lname, String state, String twitterid, String positionId){

          Candidate__c entToInsert = createCandidateWithPosition(name, fname, city, email, lname, state, twitterid, positionId);
          insert entToInsert;
          return entToInsert;

    }

    public static Position__c insertPosition(String name, String recStatus){

          Position__c entToInsert = createPosition(name, recStatus);
          insert entToInsert;
          return entToInsert;

    }

    public static Interview__c insertInterview(String candidateId, String recType, String recStatus){

          Interview__c entToInsert = createInterview(candidateId, recType, recStatus);
          insert entToInsert;
          return entToInsert;

    }

    public static Interviewer__c insertInterviewer(String interviewId){

          Interviewer__c entToInsert = createInterviewer(interviewId);
          insert entToInsert;
          return entToInsert;

    }
    
    public static Offer__c insertOffer(String candidateId, Double salary, Double bonus){

          Offer__c entToInsert = createOffer(candidateId, salary, bonus);
          insert entToInsert;
          return entToInsert;

    }

}